# Generated by Django 5.0.7 on 2024-09-03 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Image of the product', null=True, upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating of the product', max_digits=3, null=True)),
                ('material', models.CharField(blank=True, help_text='Material of the product, e.g., stainless steel', max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='Dimensions of the product, e.g., 15 x 10 x 8 inches', max_length=255, null=True)),
                ('weight', models.CharField(blank=True, help_text='Weight of the product, e.g., 5 lbs', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='Color of the product, e.g., Silver', max_length=50, null=True)),
                ('included_accessories', models.TextField(blank=True, help_text='List of included accessories, e.g., Baking tray, mixing bowl, whisk, spatula', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('payment_method', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='thebakingbreeze.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thebakingbreeze.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='thebakingbreeze.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thebakingbreeze.product')),
            ],
        ),
    ]
