# Generated by Django 5.0.7 on 2024-09-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebakingbreeze', '0002_remove_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
    ]
