# Generated by Django 5.0.7 on 2024-09-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebakingbreeze', '0004_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Price of the product', max_digits=10),
        ),
    ]
